name: Infrastructure Change
description: Propose an infrastructure change or improvement
title: "[infra]: "
labels: ["infrastructure"]
body:
  - type: markdown
    attributes:
      value: |
        Describe the infrastructure change you're proposing.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? What's the current state?
      placeholder: "Currently, X requires manual steps Y and Z. This causes..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What change are you proposing?
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - Terraform / IaC
        - Kubernetes cluster
        - ArgoCD / GitOps
        - Networking / Cilium
        - Security / Kyverno / Vault
        - Observability
        - CI/CD
        - Go tooling
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Risks and Mitigations
      description: What could go wrong? How will you handle it?

  - type: textarea
    id: rollback
    attributes:
      label: Rollback Plan
      description: How do you reverse this change if something goes wrong?
